import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header2 from "@/components/Header";
import Footer4Col from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import StoreProvider from "@/redux/store/StoreProviderClient";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <Header2 />
          {children}
          <Footer4Col />
        </StoreProvider>
      </body>
    </html>
  );
}
